language: node_js
node_js:
  - "node"
  - "8"
  - "10"
  - "12"
  - "14"
deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
notifications:
  email: false
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
