name: CI
on:
  push:
    branches: [master, try]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install Packages
        run: npm i
      - name: Lint
        run: npm run lint

  test:
    name: Test
    strategy:
      matrix:
        node: [8, 10, 12, 14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js v${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm i
    - name: Test
      run: npm run test
